export const GET_MEDICINES_REQUEST = 'GET_MEDICINES_REQUEST';
export const GET_MEDICINES_SUCCESS = 'GET_MEDICINES_SUCCESS';
export const GET_MEDICINES_FAILURE = 'GET_MEDICINES_FAILURE';

export const ADD_MEDICINE_REQUEST = 'ADD_MEDICINE_REQUEST';
export const ADD_MEDICINE_SUCCESS = 'ADD_MEDICINE_SUCCESS';
export const ADD_MEDICINE_FAILURE = 'ADD_MEDICINE_FAILURE';

export const UPDATE_MEDICINE_REQUEST = 'UPDATE_MEDICINE_REQUEST';
export const UPDATE_MEDICINE_SUCCESS = 'UPDATE_MEDICINE_SUCCESS';
export const UPDATE_MEDICINE_FAILURE = 'UPDATE_MEDICINE_FAILURE';

export const DELETE_MEDICINE_REQUEST = 'DELETE_MEDICINE_REQUEST';
export const DELETE_MEDICINE_SUCCESS = 'DELETE_MEDICINE_SUCCESS';
export const DELETE_MEDICINE_FAILURE = 'DELETE_MEDICINE_FAILURE';

export const GET_MEDICINE_INFO_REQUEST = 'GET_MEDICINE_INFO_REQUEST';
export const GET_MEDICINE_INFO_SUCCESS = 'GET_MEDICINE_INFO_SUCCESS';
export const GET_MEDICINE_INFO_FAILURE = 'GET_MEDICINE_INFO_FAILURE';

export const CLEAR_MEDICINE_INFO = 'CLEAR_MEDICINE_INFO';