export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const SEND_MEDIA_REQUEST = 'SEND_MEDIA_REQUEST';
export const SEND_MEDIA_SUCCESS = 'SEND_MEDIA_SUCCESS';
export const SEND_MEDIA_FAILURE = 'SEND_MEDIA_FAILURE';

export const CLEAR_CHAT = 'CLEAR_CHAT';
export const ADD_MESSAGE = 'ADD_MESSAGE';