export const GET_DASHBOARD_REQUEST = 'GET_DASHBOARD_REQUEST';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE';

export const GET_ADHERENCE_REQUEST = 'GET_ADHERENCE_REQUEST';
export const GET_ADHERENCE_SUCCESS = 'GET_ADHERENCE_SUCCESS';
export const GET_ADHERENCE_FAILURE = 'GET_ADHERENCE_FAILURE';