export const GET_DOSE_LOGS_REQUEST = 'GET_DOSE_LOGS_REQUEST';
export const GET_DOSE_LOGS_SUCCESS = 'GET_DOSE_LOGS_SUCCESS';
export const GET_DOSE_LOGS_FAILURE = 'GET_DOSE_LOGS_FAILURE';

export const LOG_DOSE_REQUEST = 'LOG_DOSE_REQUEST';
export const LOG_DOSE_SUCCESS = 'LOG_DOSE_SUCCESS';
export const LOG_DOSE_FAILURE = 'LOG_DOSE_FAILURE';

export const CONFIRM_DOSE_REQUEST = 'CONFIRM_DOSE_REQUEST';
export const CONFIRM_DOSE_SUCCESS = 'CONFIRM_DOSE_SUCCESS';
export const CONFIRM_DOSE_FAILURE = 'CONFIRM_DOSE_FAILURE';