export const GET_REMINDERS_REQUEST = 'GET_REMINDERS_REQUEST';
export const GET_REMINDERS_SUCCESS = 'GET_REMINDERS_SUCCESS';
export const GET_REMINDERS_FAILURE = 'GET_REMINDERS_FAILURE';

export const ADD_REMINDER_REQUEST = 'ADD_REMINDER_REQUEST';
export const ADD_REMINDER_SUCCESS = 'ADD_REMINDER_SUCCESS';
export const ADD_REMINDER_FAILURE = 'ADD_REMINDER_FAILURE';

export const UPDATE_REMINDER_REQUEST = 'UPDATE_REMINDER_REQUEST';
export const UPDATE_REMINDER_SUCCESS = 'UPDATE_REMINDER_SUCCESS';
export const UPDATE_REMINDER_FAILURE = 'UPDATE_REMINDER_FAILURE';

export const DELETE_REMINDER_REQUEST = 'DELETE_REMINDER_REQUEST';
export const DELETE_REMINDER_SUCCESS = 'DELETE_REMINDER_SUCCESS';
export const DELETE_REMINDER_FAILURE = 'DELETE_REMINDER_FAILURE';

export const TOGGLE_REMINDER_REQUEST = 'TOGGLE_REMINDER_REQUEST';
export const TOGGLE_REMINDER_SUCCESS = 'TOGGLE_REMINDER_SUCCESS';
export const TOGGLE_REMINDER_FAILURE = 'TOGGLE_REMINDER_FAILURE';